application: ebspod2
version: 1
runtime: python27
api_version: 1
threadsafe: no
handlers:

- url: /clients/.*
  login: admin
  script: main.py

- url: /episodes/
  script: main.py

- url: /programs/.*
  script: main.py

- url: .*
  script: main.py
  login: required
